name: compile and execute

'on':
  push:
  workflow_dispatch:

jobs:
  compile_and_execute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Compile
        run: ./gradlew assemble
      - name: Execute
        run: ./gradlew run
